version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.13

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache: &restore_cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests (if possible)
          command: |
            if ./node_modules/@wavo-cloud/generator-microservice/shared/util/test-checks.sh; then
              yarn ci-test
            fi

  module-push:
    docker:
      - image: circleci/node:12.13

    steps:
      - checkout

      - restore_cache: *restore_cache

      - run:
          name: Deploy (if possible)
          command: |
            if [ ! -z "${WAVO_CLOUD_WRITE_NPM_TOKEN}" ]; then
              echo "//registry.npmjs.org/:_authToken=$WAVO_CLOUD_WRITE_NPM_TOKEN" >> ~/.npmrc
              npm publish
            else
              echo "WAVO_CLOUD_WRITE_NPM_TOKEN not found. Skipping generator module push."
            fi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          context: org-global
      - module-push:
          context: org-global
          requires:
            - test

          filters:
            branches:
              only: master
